#You must replace your-url-prefix-here with your desired URL prefix in ALL THREE places below

images:
  redirect-mapping: #CHANGE ME: Only lowercase letters and hyphens
    build: Dockerfile
    retention: 3
    architecture: amd64
services:
  redirect-mapping: #CHANGE ME: Onlylowercase letters and hyphens
    image: redirect-mapping  #CHANGE ME: Only lowercase letters and hyphens
    count: 1
    cpu: 256
    memory: 512
    cluster: internal
    disable_metrics: true
    disable_fluentbit: true
    gatekeeper:
      port: 3000
      suffix: '{{ if eq .__ENV__ "dev" }}-dev{{ end }}'
      health:
        endpoint: /
    env:
      SNOWFLAKE_PRIVATE_KEY_PATH: /etc/pattern.d/snowflake_key.pem
      SNOWFLAKE_ACCOUNT: PATTERN
      SNOWFLAKE_DATABASE: PATTERN_DB
      SNOWFLAKE_SCHEMA: PUBLIC
      SNOWFLAKE_USERNAME: VIBE__APP_USER
      SNOWFLAKE_WAREHOUSE: VIBE_CODE_WH
      BIFROST_API_KEY: {{ secret "/bifrost_api_key" }}
    configs:
      snowflake_key.pem: configs/snowflake_key.pem.tmpl